# Generated by Django 4.2.30 on 2026-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bagmodel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('caption', models.TextField()),
                ('attributes', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bagmodel_english_json',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding_openai', models.JSONField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pantsmodel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('caption', models.TextField()),
                ('attributes', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pantsmodel_english_json',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding_openai', models.JSONField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoesmodel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('caption', models.TextField()),
                ('attributes', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shoesmodel_english_json',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding_openai', models.JSONField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tshirtmodel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('caption', models.TextField()),
                ('attributes', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_BGE', models.JSONField(blank=True, null=True)),
                ('embedding_jina', models.JSONField(blank=True, null=True)),
                ('embedding_tooka', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tshirtmodel_english_desc',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_openai', models.JSONField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tshirtmodel_english_json',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_fa', models.TextField()),
                ('description', models.TextField()),
                ('image_link', models.URLField(max_length=300)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('embedding_openai', models.JSONField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
